### ISSUE TITLE
Some entities not being published to MQTT / Weird naming issue

### ISSUE THREAD

**Issue by rohankapoorcom** [koying/mqtt_discoverystream_ha#13]
Hi,

Thanks for putting together this awesome integration. I'm running into a couple of problems and was hoping you would have some ideas on where to begin troubleshooting. I've added my config below in a code block.

1. Some entities of the type "light" are not being published to MQTT (though other lights are being published successfully). From the config pasted below, the two lights that are not working are:
```
- light.office_play_gradient_tube
- light.office_shelf_lightstrip
```
2. Entities of type `fan`, `button`, `script`, `input_boolean` are showing up as published to MQTT but are not generating a discovery config. Are they unsupported? Happy to contribute if that's the case and you can point me to where they should be added.
4.  Some entities have their names concatenated weirdly. For example `sensor.standing_desk_desk_height` is becoming `sensor.standing_desk_standing_desk_desk_height` and it's friendly name is becoming 'Standing Desk Standing Desk Desk Height". Other entities don't have any such issue.

Thanks for your help!

```
mqtt_discoverystream:
  base_topic: homeassistant-bitfocus-companion
  publish_attributes: true
  publish_timestamps: false
  publish_discovery: true
  include:
    entities:
      - sensor.office_temperature
      - sensor.office_humidity
      - sensor.office_illuminance
      - sensor.living_room_air_quality_score
      - fan.office_fan
      - binary_sensor.office_fan_high
      - binary_sensor.office_fan_medium
      - binary_sensor.office_fan_slow
      - button.standing_desk_preset_1
      - button.standing_desk_preset_2
      - button.standing_desk_preset_3
      - button.standing_desk_preset_4
      - sensor.standing_desk_desk_height
      - script.set_office_lights_25_percent
      - script.set_office_lights_50_percent
      - script.set_office_lights_75_percent
      - script.set_office_lights_100_percent
      - binary_sensor.office_lights_100_percent
      - binary_sensor.office_lights_75_percent
      - binary_sensor.office_lights_50_percent
      - binary_sensor.office_lights_25_percent
      - light.office_play_gradient_tube
      - light.office_shelf_lightstrip
      - light.office_desk_lower_lights
      - switch.unused_plug
      - light.left_key_light
      - light.center_key_light
      - light.office_backlighting
      - light.office_video_lights
      - switch.office_webcam_monitor
      - switch.office_ceiling_mics
      - switch.office_speakers
      - input_boolean.sentinal_headset_enabled
```
