### ISSUE TITLE
Discoverable 

### ISSUE THREAD

**Issue by pergolafabio** [koying/mqtt_discoverystream_ha#25]
Hi,

I'm using this integration to expose lights/switches  to Openhab...

```
mqtt_discoverystream_alt:
  base_topic: openhab
  publish_attributes: true
  publish_timestamps: false
  publish_discovery: true
  include:
    domains:
      - light
      - switch
```
In MQTT explorer, i see the entities being created on the base topic "openhab"

![image](https://github.com/user-attachments/assets/9411a9ce-0994-4f3a-9bdd-305646a5326f)

So far so good, but if i install OpenHab, it cant discover the entities? only the ones with hmd/homeassistant?
What am i missing here? How can i make the discoverable?

thnx
